"""Generate shift-handover reports from triaged Wazuh alerts."""
from __future__ import annotations

import csv
import io
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Sequence

from wazuh_viewer.models import Alert, TriageStatus
from wazuh_viewer.storage import TriageStore


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _now_utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _triage_summary(
    alerts: Sequence[Alert],
    store: TriageStore,
) -> dict[str, list[Alert]]:
    """Return alerts bucketed by triage status."""
    buckets: dict[str, list[Alert]] = {s.value: [] for s in TriageStatus}
    for alert in alerts:
        t = store.get(alert.alert_id)
        buckets[t.status.value].append(alert)
    return buckets


# ---------------------------------------------------------------------------
# Markdown report
# ---------------------------------------------------------------------------

def generate_markdown_report(
    alerts: Sequence[Alert],
    store: TriageStore,
    analyst_name: str = "",
    shift_label: str = "",
) -> str:
    buckets = _triage_summary(alerts, store)
    now = _now_utc()
    total = len(alerts)
    header_analyst = f" — {analyst_name}" if analyst_name else ""
    header_shift = f" ({shift_label})" if shift_label else ""

    lines: list[str] = [
        f"# Wazuh Shift Report{header_analyst}{header_shift}",
        f"",
        f"**Generated:** {now}  ",
        f"**Total alerts reviewed:** {total}",
        f"",
        f"## Status summary",
        f"",
        f"| Status | Count |",
        f"|--------|-------|",
    ]
    for status in TriageStatus:
        count = len(buckets.get(status.value, []))
        lines.append(f"| {status.label} | {count} |")

    lines += ["", "## Severity breakdown", ""]
    sev_counts: Counter[str] = Counter()
    for alert in alerts:
        sev_counts[alert.severity_label] += 1
    lines += [
        "| Severity | Count |",
        "|----------|-------|",
    ]
    for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
        lines.append(f"| {sev} | {sev_counts.get(sev, 0)} |")

    # Top rules
    rule_counts: Counter[str] = Counter(a.rule_id for a in alerts)
    top_rules = rule_counts.most_common(10)
    if top_rules:
        lines += ["", "## Top 10 triggered rules", ""]
        lines += ["| Rule ID | Count | Description |", "|---------|-------|-------------|"]
        rule_desc = {a.rule_id: a.description for a in alerts}
        for rule_id, cnt in top_rules:
            desc = rule_desc.get(rule_id, "")[:80]
            lines.append(f"| {rule_id} | {cnt} | {desc} |")

    # Top hosts
    host_counts: Counter[str] = Counter(a.host for a in alerts)
    top_hosts = host_counts.most_common(10)
    if top_hosts:
        lines += ["", "## Top 10 hosts", ""]
        lines += ["| Host | Count |", "|------|-------|"]
        for host, cnt in top_hosts:
            lines.append(f"| {host} | {cnt} |")

    # Escalated alerts detail
    escalated = buckets.get(TriageStatus.ESCALATED.value, [])
    if escalated:
        lines += ["", f"## Escalated alerts ({len(escalated)})", ""]
        lines += ["| Time | Host | Rule | Severity | Description |",
                  "|------|------|------|----------|-------------|"]
        for alert in escalated:
            t = store.get(alert.alert_id)
            ts = alert.timestamp[:19].replace("T", " ")
            lines.append(
                f"| {ts} | {alert.host} | {alert.rule_id} | {alert.severity_label} | {alert.description[:60]} |"
            )
            if t.notes:
                lines.append(f"  > **Notes:** {t.notes}")

    # Investigating
    investigating = buckets.get(TriageStatus.INVESTIGATING.value, [])
    if investigating:
        lines += ["", f"## Still investigating ({len(investigating)})", ""]
        lines += ["| Time | Host | Rule | Severity | Analyst | Notes |",
                  "|------|------|------|----------|---------|-------|"]
        for alert in investigating:
            t = store.get(alert.alert_id)
            ts = alert.timestamp[:19].replace("T", " ")
            lines.append(
                f"| {ts} | {alert.host} | {alert.rule_id} | {alert.severity_label} | {t.analyst or '—'} | {(t.notes or '')[:60]} |"
            )

    lines += ["", "---", f"*Report generated by wazughhh — {now}*", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CSV report
# ---------------------------------------------------------------------------

def generate_csv_report(
    alerts: Sequence[Alert],
    store: TriageStore,
) -> str:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow([
        "alert_id", "timestamp", "rule_id", "rule_level", "severity",
        "host", "agent_id", "mitre_ids", "description",
        "triage_status", "analyst", "notes", "updated_at",
    ])
    for alert in alerts:
        t = store.get(alert.alert_id)
        writer.writerow([
            alert.alert_id,
            alert.timestamp,
            alert.rule_id,
            alert.rule_level,
            alert.severity_label,
            alert.host,
            alert.agent_id,
            "|".join(alert.mitre_ids),
            alert.description,
            t.status.value,
            t.analyst,
            t.notes.replace("\n", " "),
            t.updated_at,
        ])
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Save helpers
# ---------------------------------------------------------------------------

def save_report(content: str, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
