"""
Generate rsyslog configuration snippets that pipe logs through mmnormalize
(liblognorm) and forward normalised JSON to Wazuh.

Typical pipeline for a device group:
  imtcp/imudp → filter by program_name → mmnormalize → template → output

Usage:
  from wazuh_viewer.rsyslog_generator import generate_rsyslog_conf
  conf = generate_rsyslog_conf(clusters, wazuh_host="10.0.0.5", wazuh_port=1514)
"""
from __future__ import annotations

from pathlib import Path
from wazuh_viewer.decoder_models import LogCluster


_HEADER = """\
# ============================================================
# rsyslog config — auto-generated by wazughhh Decoder Lab
# REVIEW BEFORE DEPLOYING
# ============================================================

module(load="mmnormalize")
module(load="omfwd")

"""

_JSON_TEMPLATE = """\
template(name="wazuh_json_fwd" type="list") {
    constant(value="{")
    constant(value="\\"@timestamp\\":")
    property(name="timereported" dateFormat="rfc3339" format="jsonf" outname="@timestamp")
    constant(value=",")
    property(name="hostname" format="jsonf" outname="hostname")
    constant(value=",")
    property(name="syslogseverity-text" format="jsonf" outname="severity")
    constant(value=",")
    property(name="programname" format="jsonf" outname="program")
    constant(value=",")
    property(name="msg" format="jsonf" outname="message")
    constant(value=",\\"fields\\":")
    property(name="$!" format="jsonf" outname="fields")
    constant(value="}")
}

"""


def _program_rule(
    program_name: str,
    rb_path: str,
    wazuh_host: str,
    wazuh_port: int,
    protocol: str,
) -> str:
    """
    Generate one rsyslog action block for a single program_name.
    Applies mmnormalize from *rb_path*, then forwards JSON to Wazuh.
    """
    safe = program_name.replace("/", "_").replace(" ", "_") or "unknown"
    return f"""\
# ---- {program_name} ----
if $programname == "{program_name}" then {{
    action(type="mmnormalize"
           rulebase="{rb_path}"
           path="$!{safe}")

    action(type="omfwd"
           target="{wazuh_host}"
           port="{wazuh_port}"
           protocol="{protocol}"
           template="wazuh_json_fwd")
}}

"""


def generate_rsyslog_conf(
    clusters: list[LogCluster],
    wazuh_host: str = "127.0.0.1",
    wazuh_port: int = 1514,
    protocol: str = "tcp",
    rb_base_dir: str = "/etc/rsyslog.d/liblognorm",
) -> str:
    """
    Generate a complete rsyslog .conf snippet for all program groups found
    in *clusters*.  Each unique program_name gets its own mmnormalize action
    pointing to `{rb_base_dir}/{program_name}.rb`.
    """
    seen: set[str] = set()
    blocks: list[str] = [_HEADER, _JSON_TEMPLATE]

    # Group clusters by program_name
    programs: dict[str, list[LogCluster]] = {}
    for c in clusters:
        prog = c.program_name or "unknown"
        programs.setdefault(prog, []).append(c)

    for prog in sorted(programs.keys()):
        if prog in seen:
            continue
        seen.add(prog)
        safe_prog = prog.replace("/", "_").replace(" ", "_")
        rb_path = f"{rb_base_dir}/{safe_prog}.rb"
        blocks.append(_program_rule(prog, rb_path, wazuh_host, wazuh_port, protocol))

    blocks.append(
        "# ============================================================\n"
        f"# Generated for {len(seen)} program(s): "
        + ", ".join(sorted(seen)) + "\n"
        "# ============================================================\n"
    )
    return "".join(blocks)


def generate_liblognorm_bundle(clusters: list[LogCluster]) -> dict[str, str]:
    """
    Return a dict of {program_name: rulebase_content} for all clusters.
    Multiple clusters with the same program_name are merged into one rulebase.
    """
    from wazuh_viewer.decoder_generator import generate_liblognorm

    bundles: dict[str, list[str]] = {}
    for c in clusters:
        prog = c.program_name or "unknown"
        bundles.setdefault(prog, []).append(generate_liblognorm(c))

    return {prog: "\n".join(parts) for prog, parts in bundles.items()}


def generate_wazuh_xml_bundle(clusters: list[LogCluster]) -> dict[str, str]:
    """
    Return a dict of {program_name: xml_content} for all clusters.
    Multiple clusters for the same program are concatenated in one XML file.
    """
    from wazuh_viewer.decoder_generator import generate_wazuh_xml

    bundles: dict[str, list[str]] = {}
    for c in clusters:
        prog = c.program_name or "unknown"
        bundles.setdefault(prog, []).append(generate_wazuh_xml(c))

    result: dict[str, str] = {}
    for prog, parts in bundles.items():
        header = "<!-- CANDIDATE — review before deploying -->\n"
        result[prog] = header + "\n\n".join(parts)
    return result
